#!/usr/bin/env bash
#
# Hook with a schedule binding: sync secrets with the 'copier: true' label from the 'copier' namespace to the other namespaces.
#

source /hooks/common/functions.sh

hook::config() {
  cat <<EOF
{
  "configVersion": "v1",
  "schedule": [
    {
      "allowFailure": true,
      "crontab": "0 3 * * *"
    }
  ]
}
EOF
}

hook::trigger() {
  # Copy secrets to the other namespaces.
  for secret in $(kubectl -n copier get secret -l copier=true -o name);
    do
    for namespace in $(kubectl get namespace -o json |
                        jq -r '.items[] |
                          select((.metadata.name == "copier" | not) and .status.phase == "Active") | .metadata.name')
    do
      kubectl -n copier get $secret -o json | \
        jq -r ".metadata.namespace=\"${namespace}\" |
                .metadata |= with_entries(select([.key] | inside([\"name\", \"namespace\", \"labels\"])))" \
        | kubectl::replace_or_create
    done
  done

  # Delete secrets with the 'copier: true' label in namespaces except 'copier', which are not exist in the 'copier' namespace.
  kubectl get secret --all-namespaces -o json | \
    jq -r '([.items[] | select(.metadata.labels."copier" == "true" and .metadata.namespace == "copier").metadata.name]) as $secrets |
             .items[] | select(.metadata.labels."copier" == "true" and .metadata.namespace != "copier" and ([.metadata.name] | inside($secrets) | not)) |
             "\(.metadata.namespace) secret \(.metadata.name)"' | \
    while read -r secret
    do
      kubectl delete -n $secret
    done
}

common::run_hook "$@"
